name: animated_segmented_tab_control
description: A customizable segmented control that can be used with a TabView.
repository: https://github.com/LanarsInc/animated-segmented-tab-control
version: 1.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
